In [13]:
import torch
from torch.utils.data import Dataset, DataLoader
data = [i for i in range(80)]

class MyDataset(Dataset): 
#创建自己的类： MyDataset,这个类是继承的torch.utils.data.Dataset
     def __init__(self,data):
        super(MyDataset,self).__init__()#对继承自父类的属性进行初始化
        self.data = data 
        
     def __getitem__(self, index):
            return self.data[index]
     def __len__(self):
            return len(self.data)

In [14]:
mydataset = MyDataset(data)
print len(mydataset)
Order_dataloader = DataLoader(dataset=mydataset,batch_size=10,shuffle=False,num_workers=1)
for i, data in enumerate(Order_dataloader):
    print(data)
    print '----'

80
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
----
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
----
tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
----
tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])
----
tensor([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
----
tensor([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])
----
tensor([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])
----
tensor([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])
----


In [16]:
print len(mydataset)
Inorder_dataloader = DataLoader(dataset=mydataset,batch_size=10,shuffle=True,num_workers=1)
for i, data in enumerate(Inorder_dataloader):
    print(data)
    print '----'

80
tensor([64, 41, 44, 22, 53, 60, 55,  8, 54, 47])
----
tensor([17, 37, 69, 48, 10, 57, 63, 46, 42, 18])
----
tensor([38, 77, 27, 29,  5, 13, 74,  0, 78, 40])
----
tensor([ 3,  2, 76, 45, 79, 25, 56, 72, 58, 24])
----
tensor([66, 67,  9, 30, 26, 71, 52, 28, 70,  6])
----
tensor([19, 21, 36, 73, 14, 11,  1, 62, 75, 15])
----
tensor([35, 33, 34, 68, 51, 49, 20,  4, 12, 61])
----
tensor([ 7, 16, 31, 65, 32, 39, 43, 59, 50, 23])
----


In [17]:
print len(mydataset)
Inorder_dataloader = DataLoader(dataset=mydataset,batch_size=10,shuffle=True,num_workers=1)
for i, data in enumerate(Inorder_dataloader):
    print(data)
    print '----'

80
tensor([63, 41, 17, 67, 79, 44, 61, 14, 47, 50])
----
tensor([72, 54,  1, 66, 64, 55,  9, 76,  3, 73])
----
tensor([42, 30, 16, 56,  8, 46, 19,  2, 28, 57])
----
tensor([51, 68, 23, 15,  0, 49, 69, 25, 29, 38])
----
tensor([40,  6, 70, 58, 32, 77, 62, 13, 10, 35])
----
tensor([65, 48,  7,  5, 45, 59, 71, 78, 75, 26])
----
tensor([22, 11, 34, 39, 24, 27,  4, 20, 21, 33])
----
tensor([43, 31, 12, 60, 52, 36, 74, 18, 53, 37])
----
